# Generated by Django 5.2.10 on 2026-01-12 13:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='question',
            new_name='qa_question_status_e6886a_idx',
            old_name='qa_question_status_created_idx',
        ),
        migrations.AddField(
            model_name='appsetting',
            name='background_color',
            field=models.CharField(default='#FFFFFF', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color like #FFFFFF', regex='^#([A-Fa-f0-9]{6})$')]),
        ),
        migrations.AddField(
            model_name='appsetting',
            name='event_title',
            field=models.CharField(default='Live Questions', max_length=200),
        ),
        migrations.AddField(
            model_name='appsetting',
            name='name_color',
            field=models.CharField(default='#444444', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color like #FFFFFF', regex='^#([A-Fa-f0-9]{6})$')]),
        ),
        migrations.AddField(
            model_name='appsetting',
            name='name_size',
            field=models.PositiveIntegerField(default=26, validators=[django.core.validators.MinValueValidator(12)]),
        ),
        migrations.AddField(
            model_name='appsetting',
            name='qr_size',
            field=models.PositiveIntegerField(default=180, validators=[django.core.validators.MinValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='appsetting',
            name='question_color',
            field=models.CharField(default='#111111', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color like #FFFFFF', regex='^#([A-Fa-f0-9]{6})$')]),
        ),
        migrations.AddField(
            model_name='appsetting',
            name='question_size',
            field=models.PositiveIntegerField(default=42, validators=[django.core.validators.MinValueValidator(18)]),
        ),
        migrations.AddField(
            model_name='appsetting',
            name='title_color',
            field=models.CharField(default='#0A699A', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color like #FFFFFF', regex='^#([A-Fa-f0-9]{6})$')]),
        ),
        migrations.AddField(
            model_name='appsetting',
            name='title_size',
            field=models.PositiveIntegerField(default=56, validators=[django.core.validators.MinValueValidator(18)]),
        ),
    ]
